// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqMPPqo2bquH2QJrjXHnuhphYWsPTCr7w',
    appId: '1:477595002172:web:f5f2a3d5cef08ceb832a39',
    messagingSenderId: '477595002172',
    projectId: 'elearn-9c315',
    authDomain: 'elearn-9c315.firebaseapp.com',
    storageBucket: 'elearn-9c315.appspot.com',
    measurementId: 'G-R9TLN9R9PL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtb-YlsOIBqwalZL0qaUfCen1rkWGPWF4',
    appId: '1:477595002172:android:1b6b2bdbc8b4ef20832a39',
    messagingSenderId: '477595002172',
    projectId: 'elearn-9c315',
    storageBucket: 'elearn-9c315.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2pjKOiE7zGbP04neR5Xgo9_ONZLfuklY',
    appId: '1:477595002172:ios:e5003de04c12d71e832a39',
    messagingSenderId: '477595002172',
    projectId: 'elearn-9c315',
    storageBucket: 'elearn-9c315.appspot.com',
    iosBundleId: 'com.example.elearnapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2pjKOiE7zGbP04neR5Xgo9_ONZLfuklY',
    appId: '1:477595002172:ios:5db11fab4b33965a832a39',
    messagingSenderId: '477595002172',
    projectId: 'elearn-9c315',
    storageBucket: 'elearn-9c315.appspot.com',
    iosBundleId: 'com.example.elearnapp.RunnerTests',
  );
}
